import { addDias, fechaISO } from '../mockCirugiaData.js';

const ok = (detalle, obligatorio = true) => ({ estado: 'ok', obligatorio, detalle });
const pendiente = (detalle, obligatorio = true) => ({ estado: 'pendiente', obligatorio, detalle });
const noRequerido = (detalle) => ({ estado: 'no-requerido', obligatorio: false, detalle });

// Solicitudes de ejemplo; las fechas tentativas son relativas a `hoy`.
// Códigos CUPS y números de autorización son placeholders a propósito.
export function crearSolicitudesMock(hoy = new Date()) {
  const f = (dias) => fechaISO(addDias(hoy, dias));
  return [
    {
      id: 'SC-1041',
      dxOrden: '[CIE-10] · Colelitiasis sintomática',
      origen: 'consulta-externa',
      medicoOrdena: 'Dr. Andrés Villamizar',
      regimen: 'Contributivo',
      contrato: '[N° contrato]',
      paciente: { nombre: 'María Fernanda Ríos Duarte', tipoDocumento: 'CC', numeroDocumento: '52.841.377', edad: 52 },
      eps: 'Sura',
      especialidad: 'Cirugía general',
      procedimiento: 'Colecistectomía laparoscópica',
      cups: '[Código CUPS]',
      cirujano: 'Dr. Andrés Villamizar',
      ordenNumero: 'OM-2026-08412',
      fechaTentativa: f(3),
      checklist: {
        orden: ok('Orden emitida el 28/09/2026 por Dr. Andrés Villamizar.'),
        autorizacion: ok('Autorización [N° autorización] vigente hasta el 30/11/2026.'),
        valoracion: ok('Valoración ASA II. Apta para anestesia general.'),
        laboratorios: ok('Hemograma, coagulación y glucosa en rango.'),
        imagenes: ok('Ecografía hepatobiliar adjunta.'),
      },
    },
    {
      id: 'SC-1042',
      dxOrden: '[CIE-10] · Gonartrosis primaria',
      origen: 'internacion',
      medicoOrdena: 'Dr. Mauricio Salamanca',
      regimen: 'Contributivo',
      contrato: '[N° contrato]',
      paciente: { nombre: 'Luis Eduardo Cárdenas Peña', tipoDocumento: 'CC', numeroDocumento: '79.455.102', edad: 67 },
      eps: 'Nueva EPS',
      especialidad: 'Ortopedia',
      procedimiento: 'Reemplazo total de rodilla',
      cups: '[Código CUPS]',
      cirujano: 'Dr. Mauricio Salamanca',
      ordenNumero: 'OM-2026-08377',
      fechaTentativa: f(7),
      checklist: {
        orden: ok('Orden emitida el 24/09/2026 por Dr. Mauricio Salamanca.'),
        autorizacion: pendiente('Solicitud [N° autorización] radicada ante Nueva EPS; sin respuesta.'),
        valoracion: ok('Valoración ASA III. Apto con control de tensión arterial.'),
        laboratorios: ok('Perfil preoperatorio completo.'),
        imagenes: ok('Radiografía de rodilla y escanograma adjuntos.'),
      },
    },
    {
      id: 'SC-1043',
      dxOrden: '[CIE-10] · Leiomioma uterino',
      origen: 'externa',
      medicoOrdena: 'Dra. Marcela Echeverri',
      regimen: 'Contributivo',
      contrato: '[N° contrato]',
      institucionRemite: '[Institución remitente]',
      paciente: { nombre: 'Ana Lucía Moreno Gil', tipoDocumento: 'CC', numeroDocumento: '43.208.964', edad: 44 },
      eps: 'Sanitas',
      especialidad: 'Ginecología',
      procedimiento: 'Histerectomía abdominal total',
      cups: '[Código CUPS]',
      cirujano: 'Dra. Marcela Echeverri',
      ordenNumero: 'OE-2026-0112',
      fechaTentativa: f(5),
      checklist: {
        orden: ok('Orden emitida el 15/09/2026 por Dra. Marcela Echeverri.'),
        autorizacion: {
          estado: 'vencida',
          obligatorio: true,
          detalle: 'Autorización [N° autorización] venció el 02/10/2026. Requiere renovación ante Sanitas.',
        },
        valoracion: pendiente('Sin valoración preanestésica registrada.'),
        laboratorios: ok('Hemograma y pruebas de coagulación en rango.'),
        imagenes: pendiente('Ecografía pélvica solicitada, sin resultado.'),
      },
    },
    {
      id: 'SC-1044',
      dxOrden: '[CIE-10] · Hernia inguinal unilateral',
      origen: 'consulta-externa',
      medicoOrdena: 'Dr. Andrés Villamizar',
      regimen: 'Contributivo',
      contrato: '[N° contrato]',
      paciente: { nombre: 'Jorge Iván Peñaranda Soto', tipoDocumento: 'CC', numeroDocumento: '80.113.659', edad: 38 },
      eps: 'Compensar',
      especialidad: 'Cirugía general',
      procedimiento: 'Herniorrafia inguinal',
      cups: '[Código CUPS]',
      cirujano: 'Dr. Andrés Villamizar',
      ordenNumero: 'OM-2026-08455',
      fechaTentativa: f(4),
      checklist: {
        orden: ok('Orden emitida el 30/09/2026 por Dr. Andrés Villamizar.'),
        autorizacion: ok('Autorización [N° autorización] vigente hasta el 15/12/2026.'),
        valoracion: ok('Valoración ASA I. Apto para anestesia regional.'),
        laboratorios: ok('Hemograma y glucosa en rango.'),
        imagenes: noRequerido('El procedimiento no requiere estudios de imágenes.'),
      },
    },
    {
      id: 'SC-1045',
      dxOrden: '[CIE-10] · Catarata senil',
      origen: 'consulta-externa',
      medicoOrdena: 'Dr. Ricardo Naranjo',
      regimen: 'Subsidiado',
      contrato: '[N° contrato]',
      paciente: { nombre: 'Rosa Elena Quintero Vargas', tipoDocumento: 'CC', numeroDocumento: '41.667.230', edad: 71 },
      eps: 'Coosalud',
      especialidad: 'Oftalmología',
      procedimiento: 'Facoemulsificación de catarata con lente intraocular',
      cups: '[Código CUPS]',
      cirujano: 'Dr. Ricardo Naranjo',
      ordenNumero: 'OM-2026-08501',
      fechaTentativa: f(9),
      checklist: {
        orden: pendiente('Falta registrar la orden médica en el sistema.'),
        autorizacion: pendiente('Aún no se solicita autorización a Coosalud.'),
        valoracion: pendiente('Sin valoración preanestésica registrada.'),
        laboratorios: pendiente('Glucosa y hemograma pendientes de toma.'),
        imagenes: noRequerido('El procedimiento no requiere estudios de imágenes.'),
      },
    },
    {
      id: 'SC-1046',
      dxOrden: '[CIE-10] · Neoplasia maligna de próstata',
      origen: 'internacion',
      medicoOrdena: 'Dr. Héctor Lozano',
      regimen: 'Contributivo',
      contrato: '[N° contrato]',
      paciente: { nombre: 'Carlos Alberto Mejía Rueda', tipoDocumento: 'CC', numeroDocumento: '17.329.845', edad: 63 },
      eps: 'Salud Total',
      especialidad: 'Urología',
      procedimiento: 'Prostatectomía radical',
      cups: '[Código CUPS]',
      cirujano: 'Dr. Héctor Lozano',
      ordenNumero: 'OM-2026-08433',
      fechaTentativa: f(6),
      checklist: {
        orden: ok('Orden emitida el 26/09/2026 por Dr. Héctor Lozano.'),
        autorizacion: ok('Autorización [N° autorización] vigente hasta el 05/12/2026.'),
        valoracion: ok('Valoración ASA II. Apto para anestesia general.'),
        laboratorios: ok('Perfil preoperatorio y PSA completos.'),
        imagenes: pendiente('Resonancia de próstata sin resultado. Es opcional: no bloquea la programación.', false),
      },
    },
    {
      id: 'SC-1047',
      dxOrden: '[CIE-10] · Bocio multinodular',
      origen: 'externa',
      medicoOrdena: 'Dra. Natalia Escobar',
      regimen: 'Contributivo',
      contrato: '[N° contrato]',
      institucionRemite: '[Institución remitente]',
      paciente: { nombre: 'Claudia Patricia Ospina Henao', tipoDocumento: 'CC', numeroDocumento: '31.902.576', edad: 49 },
      eps: 'Sura',
      especialidad: 'Cabeza y cuello',
      procedimiento: 'Tiroidectomía total',
      cups: '[Código CUPS]',
      cirujano: 'Dra. Natalia Escobar',
      ordenNumero: 'OE-2026-0127',
      fechaTentativa: f(8),
      checklist: {
        orden: ok('Orden emitida el 01/10/2026 por Dra. Natalia Escobar.'),
        autorizacion: ok('Autorización [N° autorización] vigente hasta el 20/12/2026.'),
        valoracion: pendiente('Valoración agendada para el 08/10/2026.'),
        laboratorios: pendiente('TSH, T4 libre y calcio pendientes de resultado.'),
        imagenes: ok('Ecografía de tiroides adjunta.'),
      },
    },
  ];
}
