import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Preview temporal de Inter (encargo explícito, "¿cómo se ve con Inter?") —
// AGENTS.md fija system-ui como única tipografía del proyecto ("nunca una
// tipografía distinta... aunque una referencia de diseño la pida"), así que
// esto es solo para ver el resultado corriendo, no una adopción definitiva.
// Revertir: borrar este import/const, la className de <html> abajo, y en
// cada body{font-family:...} de las features quitar el `var(--font-inter),`
// que se antepuso al stack de system-ui (ver AGENTS.md "Tipografía").
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es" className={`${geistSans.variable} ${geistMono.variable} ${inter.variable}`}>
      <body>{children}</body>
    </html>
  );
}
