// Datos mock de "Reservas" — disponibilidad futura de camas (encargo:
// pantalla nueva de Gestión de Camas, distinta de "Camas" que representa el
// estado ACTUAL). SEDES/AREAS propias (no se importan de mockCamasData.js) —
// mismo criterio de duplicación por pantalla que mockLimpiezaData.js.
export const SEDES = [
  { value: 'todas', label: 'Todas las sedes' },
  { value: 'central', label: 'Sede Central' },
];

export const AREAS = [
  { value: 'todas', label: 'Todas las áreas' },
  { value: 'uci', label: 'UCI' },
  { value: 'urgencias', label: 'Urgencias' },
  { value: 'hospitalizacion', label: 'Hospitalización' },
];

// Único vocabulario de estados de una reserva (encargo sección 9: Pendiente →
// Confirmada → Utilizada, con Cancelar desde Pendiente/Confirmada y Vencida
// automática desde Confirmada).
export const ESTADOS = [
  { value: 'todos', label: 'Todos' },
  { value: 'pendiente', label: 'Pendiente' },
  { value: 'confirmada', label: 'Confirmada' },
  { value: 'utilizada', label: 'Utilizada' },
  { value: 'vencida', label: 'Vencida' },
  { value: 'cancelada', label: 'Cancelada' },
];

export const PISOS = [
  { value: 'todos', label: 'Todos' },
  { value: 'piso-1', label: 'Piso 1' },
  { value: 'piso-2', label: 'Piso 2' },
  { value: 'piso-3', label: 'Piso 3' },
  { value: 'piso-4', label: 'Piso 4' },
];

export const SECTORES = [
  { value: 'todos', label: 'Todos' },
  { value: 'sector-a', label: 'Sector A' },
  { value: 'sector-b', label: 'Sector B' },
  { value: 'sector-c', label: 'Sector C' },
];

export const SEDE_LABEL = Object.fromEntries(SEDES.slice(1).map((s) => [s.value, s.label]));
export const AREA_LABEL = Object.fromEntries(AREAS.slice(1).map((a) => [a.value, a.label]));

// Usuario actual — mismo literal que `user` del `<Topbar>` (ver
// mockLimpiezaData.js) — se usa como "Creada por" al crear una reserva nueva
// desde "+ Nueva reserva".
export const USUARIO_ACTUAL = { nombre: 'Camilo Grondona', rol: 'Administrador' };

// KPIs — resumen global del día (mismo criterio que mockLimpiezaData.js): no
// se recalculan desde `RESERVAS_SEED`, son un valor fijo de ejemplo del
// encargo. A diferencia de Limpieza, acá no se les pidió reactividad en vivo
// frente a Confirmar/Utilizar/Cancelar — quedan como snapshot del día.
export const KPIS = {
  pendientes: 3,
  confirmadas: 5,
  utilizadasHoy: 4,
  vencidas: 1,
  canceladas: 2,
};

// 15 reservas en total (encargo: paginación "de 15 reservas") — las primeras
// 7 son los registros literales del encargo; RES-8..RES-15 son relleno
// realista (mismo día, mismas sedes/áreas) para que la paginación tenga
// contenido real en la página 2 en vez de un vacío artificial.
export const RESERVAS_SEED = [
  {
    id: 'RES-1',
    paciente: 'Juan Pérez',
    hc: 'HC-10480',
    cama: '301-A',
    ubicacion: 'Piso 3 · Sector A',
    piso: 'piso-3',
    sector: 'sector-a',
    sede: 'central',
    area: 'hospitalizacion',
    inicioFecha: '26/08/2025',
    inicioHora: '10:00',
    vencimientoFecha: '26/08/2025',
    vencimientoHora: '12:00',
    estado: 'confirmada',
    creadaPor: 'María Gómez',
    creadaPorRol: 'Admisiones',
    creadaElFecha: '26/08/2025',
    creadaElHora: '08:15',
  },
  {
    id: 'RES-2',
    paciente: 'Pedro Gómez',
    hc: 'HC-10481',
    cama: '202-B',
    ubicacion: 'Piso 2 · Sector B',
    piso: 'piso-2',
    sector: 'sector-b',
    sede: 'central',
    area: 'uci',
    inicioFecha: '26/08/2025',
    inicioHora: '11:00',
    vencimientoFecha: '26/08/2025',
    vencimientoHora: '13:00',
    estado: 'confirmada',
    creadaPor: 'María Gómez',
    creadaPorRol: 'Admisiones',
    creadaElFecha: '26/08/2025',
    creadaElHora: '08:20',
  },
  {
    id: 'RES-3',
    paciente: 'Ana Rodríguez',
    hc: 'HC-10482',
    cama: '105-C',
    ubicacion: 'Piso 1 · Sector C',
    piso: 'piso-1',
    sector: 'sector-c',
    sede: 'central',
    area: 'urgencias',
    inicioFecha: '26/08/2025',
    inicioHora: '14:00',
    vencimientoFecha: '26/08/2025',
    vencimientoHora: '16:00',
    estado: 'pendiente',
    creadaPor: 'Laura Torres',
    creadaPorRol: 'Admisiones',
    creadaElFecha: '26/08/2025',
    creadaElHora: '09:10',
  },
  {
    id: 'RES-4',
    paciente: 'Carlos López',
    hc: 'HC-10483',
    cama: '402-A',
    ubicacion: 'Piso 4 · Sector A',
    piso: 'piso-4',
    sector: 'sector-a',
    sede: 'central',
    area: 'hospitalizacion',
    inicioFecha: '26/08/2025',
    inicioHora: '09:00',
    vencimientoFecha: '26/08/2025',
    vencimientoHora: '11:00',
    estado: 'vencida',
    creadaPor: 'María Gómez',
    creadaPorRol: 'Admisiones',
    creadaElFecha: '26/08/2025',
    creadaElHora: '07:30',
  },
  {
    id: 'RES-5',
    paciente: 'Valentina Ruiz',
    hc: 'HC-10484',
    cama: '203-A',
    ubicacion: 'Piso 2 · Sector A',
    piso: 'piso-2',
    sector: 'sector-a',
    sede: 'central',
    area: 'uci',
    inicioFecha: '26/08/2025',
    inicioHora: '15:00',
    vencimientoFecha: '26/08/2025',
    vencimientoHora: '17:00',
    estado: 'cancelada',
    creadaPor: 'Laura Torres',
    creadaPorRol: 'Admisiones',
    creadaElFecha: '26/08/2025',
    creadaElHora: '08:45',
  },
  {
    id: 'RES-6',
    paciente: 'Diego Martínez',
    hc: 'HC-10485',
    cama: '302-B',
    ubicacion: 'Piso 3 · Sector B',
    piso: 'piso-3',
    sector: 'sector-b',
    sede: 'central',
    area: 'hospitalizacion',
    inicioFecha: '26/08/2025',
    inicioHora: '16:00',
    vencimientoFecha: '26/08/2025',
    vencimientoHora: '18:00',
    estado: 'confirmada',
    creadaPor: 'María Gómez',
    creadaPorRol: 'Admisiones',
    creadaElFecha: '26/08/2025',
    creadaElHora: '09:05',
  },
  {
    id: 'RES-7',
    paciente: 'Sofía Herrera',
    hc: 'HC-10486',
    cama: '101-A',
    ubicacion: 'Piso 1 · Sector A',
    piso: 'piso-1',
    sector: 'sector-a',
    sede: 'central',
    area: 'urgencias',
    inicioFecha: '26/08/2025',
    inicioHora: '12:30',
    vencimientoFecha: '26/08/2025',
    vencimientoHora: '14:30',
    estado: 'pendiente',
    creadaPor: 'Laura Torres',
    creadaPorRol: 'Admisiones',
    creadaElFecha: '26/08/2025',
    creadaElHora: '09:25',
  },
  {
    id: 'RES-8',
    paciente: 'Camila Restrepo',
    hc: 'HC-10487',
    cama: '104-B',
    ubicacion: 'Piso 1 · Sector B',
    piso: 'piso-1',
    sector: 'sector-b',
    sede: 'central',
    area: 'urgencias',
    inicioFecha: '26/08/2025',
    inicioHora: '07:00',
    vencimientoFecha: '26/08/2025',
    vencimientoHora: '09:00',
    estado: 'utilizada',
    creadaPor: 'María Gómez',
    creadaPorRol: 'Admisiones',
    creadaElFecha: '25/08/2025',
    creadaElHora: '17:40',
  },
  {
    id: 'RES-9',
    paciente: 'Andrés Vargas',
    hc: 'HC-10488',
    cama: '204-B',
    ubicacion: 'Piso 2 · Sector B',
    piso: 'piso-2',
    sector: 'sector-b',
    sede: 'central',
    area: 'uci',
    inicioFecha: '26/08/2025',
    inicioHora: '06:00',
    vencimientoFecha: '26/08/2025',
    vencimientoHora: '08:00',
    estado: 'utilizada',
    creadaPor: 'Laura Torres',
    creadaPorRol: 'Admisiones',
    creadaElFecha: '25/08/2025',
    creadaElHora: '19:15',
  },
  {
    id: 'RES-10',
    paciente: 'Isabella Moreno',
    hc: 'HC-10489',
    cama: '303-A',
    ubicacion: 'Piso 3 · Sector A',
    piso: 'piso-3',
    sector: 'sector-a',
    sede: 'central',
    area: 'hospitalizacion',
    inicioFecha: '26/08/2025',
    inicioHora: '08:00',
    vencimientoFecha: '26/08/2025',
    vencimientoHora: '10:00',
    estado: 'utilizada',
    creadaPor: 'María Gómez',
    creadaPorRol: 'Admisiones',
    creadaElFecha: '26/08/2025',
    creadaElHora: '06:50',
  },
  {
    id: 'RES-11',
    paciente: 'Mateo Cárdenas',
    hc: 'HC-10490',
    cama: '403-A',
    ubicacion: 'Piso 4 · Sector A',
    piso: 'piso-4',
    sector: 'sector-a',
    sede: 'central',
    area: 'hospitalizacion',
    inicioFecha: '26/08/2025',
    inicioHora: '17:00',
    vencimientoFecha: '26/08/2025',
    vencimientoHora: '19:00',
    estado: 'confirmada',
    creadaPor: 'Laura Torres',
    creadaPorRol: 'Admisiones',
    creadaElFecha: '26/08/2025',
    creadaElHora: '09:40',
  },
  {
    id: 'RES-12',
    paciente: 'Luciana Peña',
    hc: 'HC-10491',
    cama: '106-C',
    ubicacion: 'Piso 1 · Sector C',
    piso: 'piso-1',
    sector: 'sector-c',
    sede: 'central',
    area: 'urgencias',
    inicioFecha: '26/08/2025',
    inicioHora: '18:00',
    vencimientoFecha: '26/08/2025',
    vencimientoHora: '20:00',
    estado: 'pendiente',
    creadaPor: 'María Gómez',
    creadaPorRol: 'Admisiones',
    creadaElFecha: '26/08/2025',
    creadaElHora: '09:50',
  },
  {
    id: 'RES-13',
    paciente: 'Tomás Silva',
    hc: 'HC-10492',
    cama: '304-B',
    ubicacion: 'Piso 3 · Sector B',
    piso: 'piso-3',
    sector: 'sector-b',
    sede: 'central',
    area: 'hospitalizacion',
    inicioFecha: '26/08/2025',
    inicioHora: '13:00',
    vencimientoFecha: '26/08/2025',
    vencimientoHora: '15:00',
    estado: 'confirmada',
    creadaPor: 'Laura Torres',
    creadaPorRol: 'Admisiones',
    creadaElFecha: '26/08/2025',
    creadaElHora: '09:00',
  },
  {
    id: 'RES-14',
    paciente: 'Gabriela Ortiz',
    hc: 'HC-10493',
    cama: '205-A',
    ubicacion: 'Piso 2 · Sector A',
    piso: 'piso-2',
    sector: 'sector-a',
    sede: 'central',
    area: 'uci',
    inicioFecha: '25/08/2025',
    inicioHora: '20:00',
    vencimientoFecha: '25/08/2025',
    vencimientoHora: '22:00',
    estado: 'vencida',
    creadaPor: 'María Gómez',
    creadaPorRol: 'Admisiones',
    creadaElFecha: '25/08/2025',
    creadaElHora: '16:10',
  },
  {
    id: 'RES-15',
    paciente: 'Emilio Rojas',
    hc: 'HC-10494',
    cama: '102-A',
    ubicacion: 'Piso 1 · Sector A',
    piso: 'piso-1',
    sector: 'sector-a',
    sede: 'central',
    area: 'urgencias',
    inicioFecha: '25/08/2025',
    inicioHora: '19:00',
    vencimientoFecha: '25/08/2025',
    vencimientoHora: '21:00',
    estado: 'cancelada',
    creadaPor: 'Laura Torres',
    creadaPorRol: 'Admisiones',
    creadaElFecha: '25/08/2025',
    creadaElHora: '15:30',
  },
];

// Acciones del menú "⋯" por estado — solo Ver/Cancelar (encargo sección 8);
// Confirmar/Utilizar son siempre el CTA principal de la fila, nunca acá.
export const MENU_ACCIONES = {
  pendiente: [
    { action: 'ver', label: 'Ver' },
    { action: 'cancelar', label: 'Cancelar' },
  ],
  confirmada: [
    { action: 'ver', label: 'Ver' },
    { action: 'cancelar', label: 'Cancelar' },
  ],
  utilizada: [],
  vencida: [],
  cancelada: [],
};
